name: SQL Protocol Benchmark

on:
  workflow_dispatch: # Allow manual execution
  push:
  pull_request:

jobs:
  benchmark:
    name: Run SQL Protocol Benchmark
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install Clojure Tools
        uses: DeLaGuardo/setup-clojure@11.0
        with:
          cli: latest

      - name: Make benchmark script executable
        run: chmod +x scripts/run_benchmark.sh

      - name: Run SQL Protocol Benchmark
        id: run-benchmark
        run: |
          mkdir -p benchmark-results
          ./scripts/run_benchmark.sh | tee benchmark-results/output.log
        continue-on-error: true # Continue the workflow even if the benchmark fails

      - name: Copy benchmark result files
        run: |
          cp benchmark_results_*.txt benchmark-results/ || echo "No benchmark result files found"

      - name: Upload benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: benchmark-results
          retention-days: 90 # Keep results for 90 days

      - name: Summarize benchmark status
        run: |
          if [ ${{ steps.run-benchmark.outcome }} == 'success' ]; then
            echo "✅ Benchmark completed successfully"
          else
            echo "⚠️ Benchmark completed with errors - check the logs for details"
          fi
