name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: latest
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global init.defaultBranch "main"

      # Ensure no Redis processes are running
      - name: Check for running processes
        run: |
          echo "Checking for any running Redis processes..."
          ps aux | grep redis || true
          echo "Checking for any Java processes..."
          ps aux | grep java || true
          echo "Checking for port 6380 usage..."
          netstat -tulpn | grep 6380 || true
          echo "Killing any potential conflicting processes..."
          pkill -f "redis" || true
          pkill -f "java.*chrondb" || true
          sleep 3

      - name: Run non-Redis tests
        run: clojure -M:test-no-redis

      # Run all Redis tests sequentially with proper cleanup between them
      - name: Run Redis tests sequentially
        run: clojure -M:test-redis-sequential