name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: latest
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global init.defaultBranch "main"
      - name: Run tests
        run: |
          # Run tests one namespace at a time to avoid port conflicts
          clojure -M:test --namespace-regex "chrondb.core-test"
          clojure -M:test --namespace-regex "chrondb.storage.*"
          clojure -M:test --namespace-regex "chrondb.index.*"
          clojure -M:test --namespace-regex "chrondb.util.*"
          clojure -M:test --namespace-regex "chrondb.gzip.*"
          clojure -M:test --namespace-regex "chrondb.api.v1.*"
          clojure -M:test --namespace-regex "chrondb.api.server-test"
          # Run Redis tests individually to avoid port conflicts
          clojure -M:test --namespace-regex "chrondb.api.redis.*"

  coverage:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: "-XX:+UseG1GC -Xmx3g -Xms1g"
    steps:
      - uses: actions/checkout@v4
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: latest
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global init.defaultBranch "main"
      - name: List test directory
        run: |
          ls -R test/
      - name: Run coverage
        run: |
          clojure -J-XX:+UseG1GC -J-Xmx3g -J-Xms1g -M:coverage --ns-regex "chrondb.*" --test-ns-regex "chrondb.*-test"
